# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ast.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ast.proto", :syntax => :proto3) do
    add_message "ast.Value" do
      optional :t, :enum, 1, "ast.Value.Type"
      repeated :children, :message, 8, "ast.Value"
      oneof :primitive do
        optional :b, :bool, 2
        optional :u, :uint64, 3
        optional :raw, :bytes, 4
      end
    end
    add_enum "ast.Value.Type" do
      value :NIL, 0
      value :UINT64, 1
      value :BOOL, 2
      value :BYTES, 3
      value :ERROR, 4
      value :ARG, 16
      value :PARAM, 17
      value :OUT_POINT, 18
      value :CELL_INPUT, 19
      value :CELL_DEP, 20
      value :SCRIPT, 21
      value :CELL, 22
      value :TRANSACTION, 23
      value :HEADER, 24
      value :APPLY, 25
      value :REDUCE, 26
      value :LIST, 27
      value :QUERY_CELLS, 28
      value :MAP, 29
      value :FILTER, 30
      value :GET_CAPACITY, 48
      value :GET_DATA, 49
      value :GET_LOCK, 50
      value :GET_TYPE, 51
      value :GET_DATA_HASH, 52
      value :GET_OUT_POINT, 53
      value :GET_CODE_HASH, 54
      value :GET_HASH_TYPE, 55
      value :GET_ARGS, 56
      value :GET_CELL_DEPS, 57
      value :GET_HEADER_DEPS, 58
      value :GET_INPUTS, 59
      value :GET_OUTPUTS, 60
      value :GET_WITNESSES, 61
      value :GET_COMPACT_TARGET, 62
      value :GET_TIMESTAMP, 63
      value :GET_NUMBER, 64
      value :GET_EPOCH, 65
      value :GET_PARENT_HASH, 66
      value :GET_TRANSACTIONS_ROOT, 67
      value :GET_PROPOSALS_HASH, 68
      value :GET_UNCLES_HASH, 69
      value :GET_DAO, 70
      value :GET_NONCE, 71
      value :GET_HEADER, 72
      value :HASH, 73
      value :SERIALIZE_TO_CORE, 74
      value :SERIALIZE_TO_JSON, 75
      value :NOT, 76
      value :AND, 77
      value :OR, 78
      value :EQUAL, 80
      value :LESS, 81
      value :LEN, 82
      value :SLICE, 83
      value :INDEX, 84
      value :ADD, 85
      value :SUBTRACT, 86
      value :MULTIPLY, 87
      value :DIVIDE, 88
      value :MOD, 89
      value :COND, 120
      value :TAIL_RECURSION, 121
    end
    add_message "ast.Call" do
      optional :name, :string, 1
      optional :result, :message, 3, "ast.Value"
    end
    add_message "ast.Stream" do
      optional :name, :string, 1
      optional :filter, :message, 2, "ast.Value"
    end
    add_message "ast.Root" do
      repeated :calls, :message, 1, "ast.Call"
      repeated :streams, :message, 2, "ast.Stream"
    end
  end
end

module Ast
  Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("ast.Value").msgclass
  Value::Type = Google::Protobuf::DescriptorPool.generated_pool.lookup("ast.Value.Type").enummodule
  Call = Google::Protobuf::DescriptorPool.generated_pool.lookup("ast.Call").msgclass
  Stream = Google::Protobuf::DescriptorPool.generated_pool.lookup("ast.Stream").msgclass
  Root = Google::Protobuf::DescriptorPool.generated_pool.lookup("ast.Root").msgclass
end
