# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generic.proto

require 'google/protobuf'

require 'ast_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("generic.proto", :syntax => :proto3) do
    add_message "generic.GenericParams" do
      optional :name, :string, 1
      repeated :params, :message, 2, "ast.Value"
    end
  end
end

module Generic
  GenericParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("generic.GenericParams").msgclass
end
