# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: generic.proto for package 'generic'

require 'grpc'
require 'generic_pb'

module Generic
  module GenericService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'generic.GenericService'

      rpc :Call, ::Generic::GenericParams, ::Ast::Value
      rpc :Stream, ::Generic::GenericParams, stream(::Ast::Value)
    end

    Stub = Service.rpc_stub_class
  end
end
