proto:
	grpc_tools_ruby_protoc -I ../../protos --ruby_out=. --grpc_out=. ../../protos/ast.proto
	grpc_tools_ruby_protoc -I ../../protos --ruby_out=. --grpc_out=. ../../protos/generic.proto

.PHONY: proto
