// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ast.proto

package ast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Value_Type int32

const (
	// Primitive fields
	Value_UINT64 Value_Type = 0
	Value_NIL    Value_Type = 1
	Value_BOOL   Value_Type = 2
	Value_BYTES  Value_Type = 3
	// In animagus, we distinguish args and params in the following way:
	// * If a Value struct contains an arg, it will be interpretted as a
	// function, when used in constructs such as REDUCE or MAP, args acts
	// as placeholders for the values to test/transform.
	// * Params, on the other hand, denotes user input when calling RPCs,
	// for example, a user might provide an amount to transfer, or an address
	// to transfer to, those will be represented via parameters
	Value_ARG   Value_Type = 16
	Value_PARAM Value_Type = 17
	// Blockchain data structures
	Value_OUT_POINT   Value_Type = 18
	Value_CELL_INPUT  Value_Type = 19
	Value_CELL_DEP    Value_Type = 20
	Value_SCRIPT      Value_Type = 21
	Value_CELL        Value_Type = 22
	Value_TRANSACTION Value_Type = 23
	// Compound fields
	Value_APPLY  Value_Type = 24
	Value_REDUCE Value_Type = 25
	// List fields
	Value_LIST        Value_Type = 26
	Value_QUERY_CELLS Value_Type = 27
	Value_MAP         Value_Type = 28
	Value_FILTER      Value_Type = 29
	// Cell get operations
	Value_GET_CAPACITY  Value_Type = 48
	Value_GET_DATA      Value_Type = 49
	Value_GET_LOCK      Value_Type = 50
	Value_GET_TYPE      Value_Type = 51
	Value_GET_DATA_HASH Value_Type = 52
	Value_GET_OUT_POINT Value_Type = 53
	// Script get operations
	Value_GET_CODE_HASH Value_Type = 54
	Value_GET_HASH_TYPE Value_Type = 55
	Value_GET_ARGS      Value_Type = 56
	// Operations
	Value_HASH              Value_Type = 73
	Value_SERIALIZE_TO_CORE Value_Type = 74
	Value_SERIALIZE_TO_JSON Value_Type = 75
	Value_NOT               Value_Type = 76
	Value_AND               Value_Type = 77
	Value_OR                Value_Type = 78
	Value_EQUAL             Value_Type = 80
	Value_LESS              Value_Type = 81
	Value_LEN               Value_Type = 82
	Value_SLICE             Value_Type = 83
	Value_INDEX             Value_Type = 84
	Value_ADD               Value_Type = 85
	Value_SUBTRACT          Value_Type = 86
	Value_MULTIPLY          Value_Type = 87
	Value_DIVIDE            Value_Type = 88
	Value_MOD               Value_Type = 89
	// Special operations
	Value_COND Value_Type = 120
)

var Value_Type_name = map[int32]string{
	0:   "UINT64",
	1:   "NIL",
	2:   "BOOL",
	3:   "BYTES",
	16:  "ARG",
	17:  "PARAM",
	18:  "OUT_POINT",
	19:  "CELL_INPUT",
	20:  "CELL_DEP",
	21:  "SCRIPT",
	22:  "CELL",
	23:  "TRANSACTION",
	24:  "APPLY",
	25:  "REDUCE",
	26:  "LIST",
	27:  "QUERY_CELLS",
	28:  "MAP",
	29:  "FILTER",
	48:  "GET_CAPACITY",
	49:  "GET_DATA",
	50:  "GET_LOCK",
	51:  "GET_TYPE",
	52:  "GET_DATA_HASH",
	53:  "GET_OUT_POINT",
	54:  "GET_CODE_HASH",
	55:  "GET_HASH_TYPE",
	56:  "GET_ARGS",
	73:  "HASH",
	74:  "SERIALIZE_TO_CORE",
	75:  "SERIALIZE_TO_JSON",
	76:  "NOT",
	77:  "AND",
	78:  "OR",
	80:  "EQUAL",
	81:  "LESS",
	82:  "LEN",
	83:  "SLICE",
	84:  "INDEX",
	85:  "ADD",
	86:  "SUBTRACT",
	87:  "MULTIPLY",
	88:  "DIVIDE",
	89:  "MOD",
	120: "COND",
}

var Value_Type_value = map[string]int32{
	"UINT64":            0,
	"NIL":               1,
	"BOOL":              2,
	"BYTES":             3,
	"ARG":               16,
	"PARAM":             17,
	"OUT_POINT":         18,
	"CELL_INPUT":        19,
	"CELL_DEP":          20,
	"SCRIPT":            21,
	"CELL":              22,
	"TRANSACTION":       23,
	"APPLY":             24,
	"REDUCE":            25,
	"LIST":              26,
	"QUERY_CELLS":       27,
	"MAP":               28,
	"FILTER":            29,
	"GET_CAPACITY":      48,
	"GET_DATA":          49,
	"GET_LOCK":          50,
	"GET_TYPE":          51,
	"GET_DATA_HASH":     52,
	"GET_OUT_POINT":     53,
	"GET_CODE_HASH":     54,
	"GET_HASH_TYPE":     55,
	"GET_ARGS":          56,
	"HASH":              73,
	"SERIALIZE_TO_CORE": 74,
	"SERIALIZE_TO_JSON": 75,
	"NOT":               76,
	"AND":               77,
	"OR":                78,
	"EQUAL":             80,
	"LESS":              81,
	"LEN":               82,
	"SLICE":             83,
	"INDEX":             84,
	"ADD":               85,
	"SUBTRACT":          86,
	"MULTIPLY":          87,
	"DIVIDE":            88,
	"MOD":               89,
	"COND":              120,
}

func (x Value_Type) String() string {
	return proto.EnumName(Value_Type_name, int32(x))
}

func (Value_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{0, 0}
}

type Value struct {
	T Value_Type `protobuf:"varint,1,opt,name=t,proto3,enum=ast.Value_Type" json:"t,omitempty"`
	// Types that are valid to be assigned to Primitive:
	//	*Value_B
	//	*Value_U
	//	*Value_Raw
	Primitive            isValue_Primitive `protobuf_oneof:"primitive"`
	Children             []*Value          `protobuf:"bytes,8,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetT() Value_Type {
	if m != nil {
		return m.T
	}
	return Value_UINT64
}

type isValue_Primitive interface {
	isValue_Primitive()
}

type Value_B struct {
	B bool `protobuf:"varint,2,opt,name=b,proto3,oneof"`
}

type Value_U struct {
	U uint64 `protobuf:"varint,3,opt,name=u,proto3,oneof"`
}

type Value_Raw struct {
	Raw []byte `protobuf:"bytes,4,opt,name=raw,proto3,oneof"`
}

func (*Value_B) isValue_Primitive() {}

func (*Value_U) isValue_Primitive() {}

func (*Value_Raw) isValue_Primitive() {}

func (m *Value) GetPrimitive() isValue_Primitive {
	if m != nil {
		return m.Primitive
	}
	return nil
}

func (m *Value) GetB() bool {
	if x, ok := m.GetPrimitive().(*Value_B); ok {
		return x.B
	}
	return false
}

func (m *Value) GetU() uint64 {
	if x, ok := m.GetPrimitive().(*Value_U); ok {
		return x.U
	}
	return 0
}

func (m *Value) GetRaw() []byte {
	if x, ok := m.GetPrimitive().(*Value_Raw); ok {
		return x.Raw
	}
	return nil
}

func (m *Value) GetChildren() []*Value {
	if m != nil {
		return m.Children
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_B)(nil),
		(*Value_U)(nil),
		(*Value_Raw)(nil),
	}
}

type Call struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Result               *Value   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{1}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Call) GetResult() *Value {
	if m != nil {
		return m.Result
	}
	return nil
}

type Stream struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Filter               *Value   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{2}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stream) GetFilter() *Value {
	if m != nil {
		return m.Filter
	}
	return nil
}

type Root struct {
	Calls                []*Call   `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	Streams              []*Stream `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Root) Reset()         { *m = Root{} }
func (m *Root) String() string { return proto.CompactTextString(m) }
func (*Root) ProtoMessage()    {}
func (*Root) Descriptor() ([]byte, []int) {
	return fileDescriptor_37b5b141da493253, []int{3}
}

func (m *Root) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Root.Unmarshal(m, b)
}
func (m *Root) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Root.Marshal(b, m, deterministic)
}
func (m *Root) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Root.Merge(m, src)
}
func (m *Root) XXX_Size() int {
	return xxx_messageInfo_Root.Size(m)
}
func (m *Root) XXX_DiscardUnknown() {
	xxx_messageInfo_Root.DiscardUnknown(m)
}

var xxx_messageInfo_Root proto.InternalMessageInfo

func (m *Root) GetCalls() []*Call {
	if m != nil {
		return m.Calls
	}
	return nil
}

func (m *Root) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

func init() {
	proto.RegisterEnum("ast.Value_Type", Value_Type_name, Value_Type_value)
	proto.RegisterType((*Value)(nil), "ast.Value")
	proto.RegisterType((*Call)(nil), "ast.Call")
	proto.RegisterType((*Stream)(nil), "ast.Stream")
	proto.RegisterType((*Root)(nil), "ast.Root")
}

func init() { proto.RegisterFile("ast.proto", fileDescriptor_37b5b141da493253) }

var fileDescriptor_37b5b141da493253 = []byte{
	// 661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xdd, 0x72, 0xd3, 0x3a,
	0x10, 0xae, 0x13, 0x27, 0x4d, 0x94, 0xfe, 0x6c, 0x75, 0x4e, 0xcf, 0x31, 0x3f, 0x1d, 0x32, 0x61,
	0xca, 0xe4, 0x2a, 0x81, 0xb6, 0x14, 0xae, 0x18, 0x14, 0x5b, 0x34, 0x6a, 0x1d, 0xdb, 0x95, 0xe4,
	0xd2, 0xf4, 0x26, 0xe3, 0x14, 0xd3, 0x1a, 0x9c, 0x26, 0x13, 0x3b, 0x50, 0x9e, 0x8e, 0x67, 0xe0,
	0x8d, 0x18, 0x29, 0x98, 0x0e, 0x30, 0xdc, 0xf9, 0xfb, 0xd1, 0xb7, 0xeb, 0xd5, 0x0a, 0xd5, 0xa3,
	0x2c, 0xef, 0xcc, 0xe6, 0xd3, 0x7c, 0x8a, 0xcb, 0x51, 0x96, 0xb7, 0xbe, 0x55, 0x50, 0xe5, 0x2c,
	0x4a, 0x17, 0x31, 0xde, 0x41, 0x46, 0x6e, 0x19, 0x4d, 0xa3, 0xbd, 0xb1, 0xb7, 0xd9, 0x51, 0x2e,
	0x4d, 0x77, 0xe4, 0x97, 0x59, 0xcc, 0x8d, 0x1c, 0x6f, 0x20, 0x63, 0x6c, 0x95, 0x9a, 0x46, 0xbb,
	0xd6, 0x5f, 0xe1, 0xc6, 0x58, 0xe1, 0x85, 0x55, 0x6e, 0x1a, 0x6d, 0x53, 0xe1, 0x05, 0xc6, 0xa8,
	0x3c, 0x8f, 0x3e, 0x5b, 0x66, 0xd3, 0x68, 0xaf, 0xf5, 0x57, 0xb8, 0x02, 0xf8, 0x09, 0xaa, 0x5d,
	0x5e, 0x27, 0xe9, 0xbb, 0x79, 0x7c, 0x63, 0xd5, 0x9a, 0xe5, 0x76, 0x63, 0x0f, 0xdd, 0x25, 0xf3,
	0x9f, 0x5a, 0xeb, 0xab, 0x89, 0x4c, 0x55, 0x07, 0x23, 0x54, 0x0d, 0x99, 0x27, 0x0f, 0x0f, 0x60,
	0x05, 0xaf, 0xa2, 0xb2, 0xc7, 0x5c, 0x30, 0x70, 0x0d, 0x99, 0x3d, 0xdf, 0x77, 0xa1, 0x84, 0xeb,
	0xa8, 0xd2, 0x1b, 0x4a, 0x2a, 0xa0, 0xac, 0x54, 0xc2, 0x8f, 0x00, 0x14, 0x17, 0x10, 0x4e, 0x06,
	0xb0, 0x85, 0xd7, 0x51, 0xdd, 0x0f, 0xe5, 0x28, 0xf0, 0x99, 0x27, 0x01, 0xe3, 0x0d, 0x84, 0x6c,
	0xea, 0xba, 0x23, 0xe6, 0x05, 0xa1, 0x84, 0x7f, 0xf0, 0x1a, 0xaa, 0x69, 0xec, 0xd0, 0x00, 0xfe,
	0x55, 0xa5, 0x84, 0xcd, 0x59, 0x20, 0x61, 0x5b, 0x55, 0x50, 0x0a, 0xfc, 0x87, 0x37, 0x51, 0x43,
	0x72, 0xe2, 0x09, 0x62, 0x4b, 0xe6, 0x7b, 0xf0, 0xbf, 0x8a, 0x27, 0x41, 0xe0, 0x0e, 0xc1, 0x52,
	0x27, 0x38, 0x75, 0x42, 0x9b, 0xc2, 0x3d, 0x75, 0xc2, 0x65, 0x42, 0xc2, 0x7d, 0x75, 0xe2, 0x34,
	0xa4, 0x7c, 0x38, 0x52, 0x09, 0x02, 0x1e, 0xa8, 0xce, 0x06, 0x24, 0x80, 0x87, 0xca, 0xff, 0x86,
	0xb9, 0x92, 0x72, 0xd8, 0xc1, 0x80, 0xd6, 0x8e, 0xa8, 0x1c, 0xd9, 0x24, 0x20, 0x36, 0x93, 0x43,
	0x78, 0xaa, 0xba, 0x51, 0x8c, 0x43, 0x24, 0x81, 0x67, 0x05, 0x72, 0x7d, 0xfb, 0x04, 0xf6, 0x0a,
	0x24, 0x87, 0x01, 0x85, 0x7d, 0xbc, 0x85, 0xd6, 0x0b, 0xe7, 0xa8, 0x4f, 0x44, 0x1f, 0x0e, 0x0a,
	0xea, 0xee, 0x6f, 0x9f, 0x17, 0x94, 0xed, 0x3b, 0x74, 0xe9, 0x3a, 0x2c, 0x28, 0x85, 0x96, 0x59,
	0x2f, 0x8a, 0x64, 0xc2, 0x8f, 0x04, 0xbc, 0x54, 0x7f, 0xa1, 0xad, 0x0c, 0x6f, 0xa3, 0x2d, 0x41,
	0x39, 0x23, 0x2e, 0xbb, 0xa0, 0x23, 0xe9, 0x8f, 0x6c, 0x9f, 0x53, 0x38, 0xfe, 0x83, 0x3e, 0x16,
	0xbe, 0x07, 0x27, 0xfa, 0x6a, 0x7c, 0x09, 0xae, 0xbe, 0x05, 0xcf, 0x81, 0x01, 0xae, 0xa2, 0x92,
	0xcf, 0xc1, 0x53, 0xe3, 0xa2, 0xa7, 0x21, 0x71, 0x21, 0xd0, 0x23, 0xa2, 0x42, 0xc0, 0xa9, 0x72,
	0xb9, 0xd4, 0x03, 0xae, 0x54, 0xe1, 0x32, 0x9b, 0x82, 0x50, 0x9f, 0xcc, 0x73, 0xe8, 0x39, 0x48,
	0x1d, 0xe2, 0x38, 0x10, 0xaa, 0xe6, 0x44, 0xd8, 0x93, 0x9c, 0xd8, 0x12, 0xce, 0x14, 0x1a, 0x84,
	0xae, 0x64, 0x6a, 0xf8, 0x6f, 0xd5, 0x30, 0x1d, 0x76, 0xc6, 0x1c, 0x0a, 0xe7, 0x7a, 0xc2, 0xbe,
	0x03, 0x43, 0x7d, 0x6f, 0xbe, 0xe7, 0xc0, 0x6d, 0xaf, 0x81, 0xea, 0xb3, 0x79, 0x32, 0x49, 0xf2,
	0xe4, 0x53, 0xdc, 0x7a, 0x85, 0x4c, 0x3b, 0x4a, 0x53, 0x8c, 0x91, 0x79, 0x13, 0x4d, 0x62, 0xbd,
	0xd4, 0x75, 0xae, 0xbf, 0x71, 0x0b, 0x55, 0xe7, 0x71, 0xb6, 0x48, 0x73, 0xbd, 0xbb, 0xbf, 0x2e,
	0xe4, 0x0f, 0xa5, 0xf5, 0x1a, 0x55, 0x45, 0x3e, 0x8f, 0xa3, 0xc9, 0xdf, 0x12, 0xde, 0x27, 0x69,
	0x1e, 0xcf, 0xf5, 0x6b, 0xf8, 0x2d, 0x61, 0xa9, 0xb4, 0x3c, 0x64, 0xf2, 0xe9, 0x34, 0xc7, 0x8f,
	0x50, 0xe5, 0x32, 0x4a, 0xd3, 0xcc, 0x32, 0xf4, 0xf6, 0xd7, 0xb5, 0x55, 0xf5, 0xc6, 0x97, 0x3c,
	0xde, 0x45, 0xab, 0x99, 0x2e, 0x95, 0x59, 0x25, 0x6d, 0x69, 0x68, 0xcb, 0xb2, 0x3c, 0x2f, 0xb4,
	0xde, 0xee, 0xc5, 0xe3, 0xab, 0x24, 0xbf, 0x5e, 0x8c, 0x3b, 0x97, 0xd3, 0x49, 0xf7, 0xf6, 0x76,
	0x11, 0x7f, 0x48, 0xe2, 0x6e, 0x74, 0x93, 0x4c, 0xa2, 0xab, 0x45, 0xd6, 0x9d, 0x7d, 0xbc, 0xea,
	0x46, 0x59, 0x3e, 0xae, 0xea, 0x87, 0xbd, 0xff, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xd8, 0x59,
	0x8e, 0xe5, 0x03, 0x00, 0x00,
}
